/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MCQQuestion = IDL.Record({
  'id' : IDL.Nat,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'language' : IDL.Text,
  'examCategory' : IDL.Text,
  'option1' : IDL.Text,
  'option2' : IDL.Text,
  'option3' : IDL.Text,
  'option4' : IDL.Text,
});
export const TypingPassage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'wordCount' : IDL.Nat,
  'language' : IDL.Text,
  'examCategory' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TypingResult = IDL.Record({
  'wpm' : IDL.Nat,
  'duration' : IDL.Nat,
  'isPractice' : IDL.Bool,
  'userId' : IDL.Text,
  'examCategory' : IDL.Text,
  'timestamp' : IDL.Int,
  'passageId' : IDL.Nat,
  'attemptNumber' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const MCQResult = IDL.Record({
  'isPractice' : IDL.Bool,
  'userId' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'examCategory' : IDL.Text,
  'timestamp' : IDL.Int,
  'attemptNumber' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMCQQuestion' : IDL.Func([MCQQuestion], [], []),
  'addPassage' : IDL.Func([TypingPassage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQQuestion)], ['query']),
  'getAllPassages' : IDL.Func([], [IDL.Vec(TypingPassage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(TypingResult)], ['query']),
  'getLeaderboardByExam' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TypingResult)],
      ['query'],
    ),
  'getMCQsByExam' : IDL.Func([IDL.Text], [IDL.Vec(MCQQuestion)], ['query']),
  'getMCQsByExamAndLanguage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MCQQuestion)],
      ['query'],
    ),
  'getPassagesByExam' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TypingPassage)],
      ['query'],
    ),
  'getPassagesByExamAndLanguage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TypingPassage)],
      ['query'],
    ),
  'getUserMCQResults' : IDL.Func([IDL.Text], [IDL.Vec(MCQResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTypingResults' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TypingResult)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMCQResult' : IDL.Func([MCQResult], [], []),
  'saveTypingResult' : IDL.Func([TypingResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MCQQuestion = IDL.Record({
    'id' : IDL.Nat,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'language' : IDL.Text,
    'examCategory' : IDL.Text,
    'option1' : IDL.Text,
    'option2' : IDL.Text,
    'option3' : IDL.Text,
    'option4' : IDL.Text,
  });
  const TypingPassage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'wordCount' : IDL.Nat,
    'language' : IDL.Text,
    'examCategory' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TypingResult = IDL.Record({
    'wpm' : IDL.Nat,
    'duration' : IDL.Nat,
    'isPractice' : IDL.Bool,
    'userId' : IDL.Text,
    'examCategory' : IDL.Text,
    'timestamp' : IDL.Int,
    'passageId' : IDL.Nat,
    'attemptNumber' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const MCQResult = IDL.Record({
    'isPractice' : IDL.Bool,
    'userId' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'examCategory' : IDL.Text,
    'timestamp' : IDL.Int,
    'attemptNumber' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMCQQuestion' : IDL.Func([MCQQuestion], [], []),
    'addPassage' : IDL.Func([TypingPassage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQQuestion)], ['query']),
    'getAllPassages' : IDL.Func([], [IDL.Vec(TypingPassage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(TypingResult)], ['query']),
    'getLeaderboardByExam' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TypingResult)],
        ['query'],
      ),
    'getMCQsByExam' : IDL.Func([IDL.Text], [IDL.Vec(MCQQuestion)], ['query']),
    'getMCQsByExamAndLanguage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MCQQuestion)],
        ['query'],
      ),
    'getPassagesByExam' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TypingPassage)],
        ['query'],
      ),
    'getPassagesByExamAndLanguage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TypingPassage)],
        ['query'],
      ),
    'getUserMCQResults' : IDL.Func([IDL.Text], [IDL.Vec(MCQResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTypingResults' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TypingResult)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMCQResult' : IDL.Func([MCQResult], [], []),
    'saveTypingResult' : IDL.Func([TypingResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };