/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MCQQuestion {
  'id' : bigint,
  'correctAnswer' : bigint,
  'questionText' : string,
  'language' : string,
  'examCategory' : string,
  'option1' : string,
  'option2' : string,
  'option3' : string,
  'option4' : string,
}
export interface MCQResult {
  'isPractice' : boolean,
  'userId' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'examCategory' : string,
  'timestamp' : bigint,
  'attemptNumber' : bigint,
}
export interface TypingPassage {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'wordCount' : bigint,
  'language' : string,
  'examCategory' : string,
}
export interface TypingResult {
  'wpm' : bigint,
  'duration' : bigint,
  'isPractice' : boolean,
  'userId' : string,
  'examCategory' : string,
  'timestamp' : bigint,
  'passageId' : bigint,
  'attemptNumber' : bigint,
  'accuracy' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMCQQuestion' : ActorMethod<[MCQQuestion], undefined>,
  'addPassage' : ActorMethod<[TypingPassage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIsAdmin' : ActorMethod<[], boolean>,
  'getAllMCQs' : ActorMethod<[], Array<MCQQuestion>>,
  'getAllPassages' : ActorMethod<[], Array<TypingPassage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<TypingResult>>,
  'getLeaderboardByExam' : ActorMethod<[string], Array<TypingResult>>,
  'getMCQsByExam' : ActorMethod<[string], Array<MCQQuestion>>,
  'getMCQsByExamAndLanguage' : ActorMethod<
    [string, string],
    Array<MCQQuestion>
  >,
  'getPassagesByExam' : ActorMethod<[string], Array<TypingPassage>>,
  'getPassagesByExamAndLanguage' : ActorMethod<
    [string, string],
    Array<TypingPassage>
  >,
  'getUserMCQResults' : ActorMethod<[string], Array<MCQResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTypingResults' : ActorMethod<[string], Array<TypingResult>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMCQResult' : ActorMethod<[MCQResult], undefined>,
  'saveTypingResult' : ActorMethod<[TypingResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];